wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1691851626.972497
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 13
      - 23
      4: 3.8.16
      5: 0.15.8
      8:
      - 2
      - 5
nhead:
  desc: null
  value: 8
num_layers:
  desc: null
  value: 6
early_stop:
  desc: null
  value: true
num_epochs:
  desc: null
  value: 2
mask_generator_type:
  desc: null
  value: zoom
clip_model:
  desc: null
  value: ViT-L/14
mask_ratio:
  desc: null
  value: 70
model_type:
  desc: null
  value: linear
device:
  desc: null
  value: cuda:0
